<?php
$username = $form->get('username');
$username->setAttribute('placeholder', 'username');

$password = $form->get('password');
$password->setAttribute('placeholder', 'password');

$form->prepare();
?>

<div class="login-page">
    <div class="form">

        <form class="register-form" method="POST" name="register" action="/authentication/register">
            <?= $this->formElement($username) ?>
            <?= $this->formElement($password) ?>
            <button type="submit">create</button>
            <p class="message">Already registered? <a href="#">Sign In</a></p>
        </form>
        <form class="login-form" method="POST" name="login" action="/authentication/login">
            <?= $this->formElement($username) ?>
            <?= $this->formElement($password) ?>
            <button type="submit">login</button>
            <p class="message">Not registered? <a href="#">Create an account</a></p>
        </form>

    </div>
</div>

<?= $this->form()->closeTag() ?>
