<?php
$aclService = $this->layout()->getVariable('aclService');
?>
<h1 style="margin-top:75px;">Blog</h1>

<div class="list-group">
<?php foreach ($this->posts as $post) : ?>
  <div class="list-group-item">
    <h4 class="list-group-item-heading">
      <a href="<?= $this->url('blog/detail', ['id' => $post->getId()]) ?>">
        <?= $post->getTitle() ?>
      </a>
    </h4>

    <div
    class="btn-group"
    role="group"
    aria-label="Post actions"
    style="<?= ! $aclService->isAllowed('artist', 'edit') ? 'display:none' : '' ?>"
    >
      <a class="btn btn-xs btn-default" href="<?= $this->url('blog/edit', ['id' => $post->getId()]) ?>">Edit</a>
      <a class="btn btn-xs btn-danger" href="<?= $this->url('blog/delete', ['id' => $post->getId()]) ?>">Delete</a>
    </div>
  </div>
<?php endforeach ?>
</div>

<div class="btn-group" role="group" aria-label="Post actions">
  <a
    class="btn btn-primary"
    href="<?= $this->url('blog/add') ?>"
    style="<?= ! $aclService->isAllowed('blog', 'add') ? 'display:none' : '' ?>"
  >
    Write new post
  </a>
</div>
