<?php
$title = $this->translator->translate('My albums');
$this->headTitle($title);
$adminMode = $this->layout()->getVariable('adminMode');
?>
<h1 style="margin-top:75px;"><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('album', ['action' => 'add']) ?>">
        <?php
        if ($adminMode) {
            echo $this->translator->translate('Add new album');
        }
        ?>
    </a>
</p>

<table class="table">
    <tr>
        <th><?= $this->translator->translate('Title') ?></th>
        <th><?= $this->translator->translate('Artist') ?></th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->paginator as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml($album->title) ?></td>
            <td>
                <a
                    <?php
                    if (true === $adminMode) {
                        'href="' . $this->url('artist/edit', ['id' => $album->artistId]) . '"';
                    }
                    ?>
                >
                    <?= $this->escapeHtml($this->table->getArtist($album)->getName()) ?>
                </a>
            </td>
            <td>
                <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">
                    <?php
                    if (true === $adminMode) {
                        echo $this->translator->translate('Edit');
                    }
                    ?>
                </a>
                <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">
                    <?php
                    if (true === $adminMode) {
                        echo $this->translator->translate('Delete');
                    }
                    ?>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?= $this->paginationControl(
    // The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'album']
) ?>
