<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/0.8.2/css/flag-icon.min.css')
            ->prependStylesheet(
                'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.2/css/bootstrap-select.min.css'
            )
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet('css/alert-message.css')
            ->prependStylesheet('css/language-select.css')
            ->prependStylesheet('css/authentication/logout-button.css')
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/authentication/logout-button.js'))
            ->prependFile($this->basePath('js/alert-message.js'))
            ->prependFile($this->basePath('js/language-select.js'))
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.2/js/bootstrap-select.min.js')
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="breadcrumb-container">
                    <?= $this->navigation('navigation')
                            ->breadcrumbs()
                            ->setMinDepth(0)
                            ->setPartial('partial/breadcrumb') ?>
                </div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <?= $this->navigation('navigation')
                        ->menu()
                        ->setTranslator($this->translator)
                        ->setTranslatorEnabled(true)
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav') ?>
                    <select class="SelectPicker language-select-picker selectpicker" data-width="fit">
                        <option
                            selected value="en_US"
                            data-content='<span class="flag-icon flag-icon-us"></span> English'
                        >
                            English
                        </option>
                        <option value="de_DE" data-content='<span class="flag-icon flag-icon-de"></span> Deutsche'>
                            Deutsche
                        </option>
                    </select>
                    <button class="logoutButton btn btn-danger logout-button">Log out</button>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="message-box">
                <?php foreach ($this->flashMessenger()->getMessages() as $message) : ?>
                    <div class="alert-<?= $message->getType() ?>">
                        <?= $message->getContent() ?>
                        <button class="alertMessageCloseButton btn-default btn-alert-close">x</button>
                    </div>
                <?php endforeach; ?>
            </div>

            <?= $this->content ?>
            <hr>
            <footer>
                <p>
                    &copy; 2005 - <?= date('Y') ?>
                    <?= $this->translator->translate('by Zend Technologies Ltd. All rights reserved.') ?>
                </p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
