<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/0.8.2/css/flag-icon.min.css')
            ->prependStylesheet(
                'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.2/css/bootstrap-select.min.css'
            )
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <?= $this->headLink()->prependStylesheet('css/alert-message.css') ?>
        <?= $this->headLink()->prependStylesheet('css/language-select.css') ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.2/js/bootstrap-select.min.js')
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
        <?= $this->headScript()->prependFile($this->basePath('js/alert-message.js')) ?>
        <?= $this->headScript()->prependFile($this->basePath('js/language-select.js')) ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <?= $this->navigation('navigation')
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setPartial('partial/breadcrumb') ?>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <?= $this->navigation('navigation')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav') ?>
                    <select class="SelectPicker language-select-picker selectpicker" data-width="fit">
                        <option data-content='<span class="flag-icon flag-icon-us"></span> English'>English</option>
                        <option  data-content='<span class="flag-icon flag-icon-de"></span> Deutsche'>Deutsche</option>
                    </select>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="message-box">
                <?php foreach ($this->flashMessenger()->getMessages() as $message) : ?>
                    <div class="alert-<?= $message->getType() ?>">
                        <?= $message->getContent() ?>
                        <button class="alertMessageCloseButton btn-default btn-alert-close">x</button>
                    </div>
                <?php endforeach; ?>
            </div>

            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
