<h1 style="margin-top:75px;">Delete artist</h1>

<p>Are you sure you want to delete the following artist?</p>

<ul class="list-group">
    <li class="list-group-item"><?= $this->escapeHtml($this->artist->getName()) ?></li>
</ul>

<form action="<?php $this->url('artist/delete', [], true) ?>" method="post">
    <input type="hidden" name="id" value="<?= $this->escapeHtmlAttr($this->artist->getId()) ?>" />
    <input class="btn btn-default" type="submit" name="confirm" value="Cancel" />
    <input class="btn btn-danger" type="submit" name="confirm" value="Delete" />
</form>
