<?php
$form = $this->form;
$fieldset = $form->get('post');

$name = $fieldset->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Artist name');

$birthday = $fieldset->get('birthday');
$birthday->setAttribute('class', 'form-control');
$birthday->setAttribute('placeholder', 'Artist birthday');

$isMarried = $fieldset->get('isMarried');

$submit = $form->get('submit');
$submit->setValue($this->submitLabel);
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>

<fieldset>
<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($birthday) ?>
    <?= $this->formElement($birthday) ?>
    <?= $this->formElementErrors()->render($birthday, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($isMarried) ?>
    <?= $this->formElement($isMarried) ?>
    <?= $this->formElementErrors()->render($isMarried, ['class' => 'help-block']) ?>
</div>

</fieldset>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($fieldset->get('id'));
echo $this->form()->closeTag();
